### ISSUE TITLE
환경 변수 파일 config.txt는 어디서 처리해주나요?

### ISSUE THREAD

**Issue by mindrare** [ekgns33/2023_KU_project2#9]
프로그램 실행 시 얘도 한번 체크해야 하는데 ProjectManager에서 그러면 super()를 두 번 호출해서 phonebook.txt와 config.txt를 처리하나요? FIleHandler와 ContactMapper에서도 config.txt 파일을 처리하는 코드가 더 필요한가요?

**Comment by ParkSeongGeun** [comment]
아직 설정메뉴를 구현하지 않아서 코드 내에서 구현이 안된 거 같아요.
